// Pure part of `npm run images:audit`: compares the paths the database points
// at with the objects in each bucket and renders docs/images-audit.md.

import type { ImageReference, StorageObject } from './supabase-script.ts'
import { formatBytes } from './util.ts'

export interface HeadResult {
  status: number
  contentType: string | null
  bytes: number | null
  etag: string | null
}

export interface FormatStats {
  count: number
  bytes: number
  maxBytes: number
}

export interface BucketAudit {
  bucket: string
  rows: number
  objects: number
  bytes: number
  byFormat: Record<string, FormatStats>
  /** Referenced by a row but not in the bucket. */
  missing: ImageReference[]
  /** In the bucket but no row points at it. */
  orphans: StorageObject[]
  /** One path referenced by more than one row. */
  sharedPaths: { path: string; rows: string[] }[]
  /** Different paths with identical content (same ETag and size). */
  duplicates: { etag: string; bytes: number; paths: string[] }[]
  /** Public URL didn't serve 200, or served a different size than listed. */
  headProblems: { path: string; problem: string }[]
  cacheControl: Record<string, number>
}

export function headKey(bucket: string, path: string): string {
  return `${bucket}/${path}`
}

function formatOf(object: StorageObject, head: HeadResult | undefined): string {
  const type = head?.contentType ?? object.mimetype
  if (!type) return 'unknown'
  return type
    .replace(/^image\//, '')
    .split(';')[0]
    .trim()
}

export function auditBucket(
  bucket: string,
  refs: ImageReference[],
  objects: StorageObject[],
  heads: Map<string, HeadResult>,
): BucketAudit {
  const bucketRefs = refs.filter((ref) => ref.bucket === bucket)
  const objectPaths = new Set(objects.map((object) => object.path))
  const refsByPath = new Map<string, ImageReference[]>()
  for (const ref of bucketRefs) {
    refsByPath.set(ref.path, [...(refsByPath.get(ref.path) ?? []), ref])
  }

  const byFormat: Record<string, FormatStats> = {}
  const byContent = new Map<string, string[]>()
  const cacheControl: Record<string, number> = {}
  const headProblems: BucketAudit['headProblems'] = []
  for (const object of objects) {
    const head = heads.get(headKey(bucket, object.path))
    const format = formatOf(object, head)
    const stats = (byFormat[format] ??= { count: 0, bytes: 0, maxBytes: 0 })
    stats.count++
    stats.bytes += object.bytes
    stats.maxBytes = Math.max(stats.maxBytes, object.bytes)

    if (object.etag) {
      const key = `${object.etag}:${object.bytes}`
      byContent.set(key, [...(byContent.get(key) ?? []), object.path])
    }
    const cache = object.cacheControl ?? '(none)'
    cacheControl[cache] = (cacheControl[cache] ?? 0) + 1
    if (!head) {
      headProblems.push({ path: object.path, problem: 'not checked' })
      continue
    }
    if (head.status !== 200)
      headProblems.push({ path: object.path, problem: `HTTP ${head.status}` })
    else if (head.bytes !== null && head.bytes !== object.bytes) {
      headProblems.push({
        path: object.path,
        problem: `serves ${head.bytes} B, listed ${object.bytes} B`,
      })
    }
  }

  return {
    bucket,
    rows: new Set(bucketRefs.map((ref) => ref.rowId)).size,
    objects: objects.length,
    bytes: objects.reduce((sum, object) => sum + object.bytes, 0),
    byFormat,
    missing: bucketRefs.filter((ref) => !objectPaths.has(ref.path)),
    orphans: objects.filter((object) => !refsByPath.has(object.path)),
    sharedPaths: [...refsByPath]
      .filter(([, list]) => list.length > 1)
      .map(([path, list]) => ({ path, rows: list.map((ref) => ref.rowId) })),
    duplicates: [...byContent]
      .filter(([, paths]) => paths.length > 1)
      .map(([key, paths]) => {
        const [etag, bytes] = key.split(':')
        return { etag, bytes: Number(bytes), paths }
      }),
    headProblems,
    cacheControl,
  }
}

function list<T>(items: T[], render: (item: T) => string, empty = 'none'): string {
  if (items.length === 0) return `${empty}\n`
  return items.map((item) => `- ${render(item)}`).join('\n') + '\n'
}

export function renderAuditMarkdown(
  audits: BucketAudit[],
  meta: { generatedAt: string; mode: string },
): string {
  const totalObjects = audits.reduce((sum, audit) => sum + audit.objects, 0)
  const totalBytes = audits.reduce((sum, audit) => sum + audit.bytes, 0)
  const lines: string[] = [
    '# Image audit',
    '',
    `Generated by \`npm run images:audit\` on ${meta.generatedAt} (connected as ${meta.mode}). ` +
      'Read-only: bucket listings, table reads and one `HEAD` per public URL; no image was downloaded.',
    '',
    `**Total: ${totalObjects} objects, ${formatBytes(totalBytes)}.**`,
    '',
    '| Bucket | Rows with a photo | Objects | Bytes | Missing | Orphans | Shared paths | Duplicate content | HEAD problems |',
    '| --- | --- | --- | --- | --- | --- | --- | --- | --- |',
    ...audits.map(
      (audit) =>
        `| \`${audit.bucket}\` | ${audit.rows} | ${audit.objects} | ${formatBytes(audit.bytes)} | ${audit.missing.length} | ` +
        `${audit.orphans.length} | ${audit.sharedPaths.length} | ${audit.duplicates.length} | ${audit.headProblems.length} |`,
    ),
    '',
  ]

  for (const audit of audits) {
    lines.push(`## \`${audit.bucket}\``, '')
    lines.push(
      '| Format | Objects | Bytes | Average | Largest |',
      '| --- | --- | --- | --- | --- |',
    )
    for (const [format, stats] of Object.entries(audit.byFormat).sort(
      ([, a], [, b]) => b.bytes - a.bytes,
    )) {
      lines.push(
        `| ${format} | ${stats.count} | ${formatBytes(stats.bytes)} | ${formatBytes(Math.round(stats.bytes / stats.count))} | ${formatBytes(stats.maxBytes)} |`,
      )
    }
    lines.push('')
    lines.push(
      '**Stored Cache-Control:** ' +
        (Object.entries(audit.cacheControl)
          .map(([value, count]) => `\`${value}\` × ${count}`)
          .join(' · ') || 'none'),
      '',
    )
    lines.push('**Missing objects** (row → path):', '')
    lines.push(list(audit.missing, (ref) => `\`${ref.table}\` \`${ref.rowId}\` → \`${ref.path}\``))
    lines.push('**Orphaned objects:**', '')
    lines.push(list(audit.orphans, (object) => `\`${object.path}\` (${formatBytes(object.bytes)})`))
    lines.push('**Paths shared by several rows:**', '')
    lines.push(
      list(audit.sharedPaths, (shared) => `\`${shared.path}\` ← ${shared.rows.length} rows`),
    )
    lines.push('**Duplicate content** (same ETag and size):', '')
    lines.push(
      list(
        audit.duplicates,
        (dup) => `${formatBytes(dup.bytes)}: ${dup.paths.map((p) => `\`${p}\``).join(', ')}`,
      ),
    )
    lines.push('**HEAD problems:**', '')
    lines.push(list(audit.headProblems, (item) => `\`${item.path}\`: ${item.problem}`))
  }
  return (
    lines
      .join('\n')
      .replace(/\n{3,}/g, '\n\n')
      .trimEnd() + '\n'
  )
}
